export interface CountryCode {
  code: string;
  country: string;
  flag: string;
  minDigits: number;
  maxDigits: number;
}

export const countryCodes: CountryCode[] = [
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦", minDigits: 9, maxDigits: 9 },
  { code: "+213", country: "Algeria", flag: "🇩🇿", minDigits: 9, maxDigits: 9 },
  { code: "+61", country: "Australia", flag: "🇦🇺", minDigits: 9, maxDigits: 9 },
  { code: "+973", country: "Bahrain", flag: "🇧🇭", minDigits: 8, maxDigits: 8 },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩", minDigits: 10, maxDigits: 10 },
  { code: "+55", country: "Brazil", flag: "🇧🇷", minDigits: 10, maxDigits: 11 },
  { code: "+86", country: "China", flag: "🇨🇳", minDigits: 11, maxDigits: 11 },
  { code: "+20", country: "Egypt", flag: "🇪🇬", minDigits: 10, maxDigits: 10 },
  { code: "+33", country: "France", flag: "🇫🇷", minDigits: 9, maxDigits: 9 },
  { code: "+49", country: "Germany", flag: "🇩🇪", minDigits: 10, maxDigits: 11 },
  { code: "+233", country: "Ghana", flag: "🇬🇭", minDigits: 9, maxDigits: 9 },
  { code: "+91", country: "India", flag: "🇮🇳", minDigits: 10, maxDigits: 10 },
  { code: "+62", country: "Indonesia", flag: "🇮🇩", minDigits: 9, maxDigits: 12 },
  { code: "+964", country: "Iraq", flag: "🇮🇶", minDigits: 10, maxDigits: 10 },
  { code: "+39", country: "Italy", flag: "🇮🇹", minDigits: 9, maxDigits: 10 },
  { code: "+81", country: "Japan", flag: "🇯🇵", minDigits: 10, maxDigits: 11 },
  { code: "+962", country: "Jordan", flag: "🇯🇴", minDigits: 9, maxDigits: 9 },
  { code: "+254", country: "Kenya", flag: "🇰🇪", minDigits: 9, maxDigits: 9 },
  { code: "+965", country: "Kuwait", flag: "🇰🇼", minDigits: 8, maxDigits: 8 },
  { code: "+961", country: "Lebanon", flag: "🇱🇧", minDigits: 7, maxDigits: 8 },
  { code: "+218", country: "Libya", flag: "🇱🇾", minDigits: 9, maxDigits: 9 },
  { code: "+60", country: "Malaysia", flag: "🇲🇾", minDigits: 9, maxDigits: 10 },
  { code: "+52", country: "Mexico", flag: "🇲🇽", minDigits: 10, maxDigits: 10 },
  { code: "+212", country: "Morocco", flag: "🇲🇦", minDigits: 9, maxDigits: 9 },
  { code: "+977", country: "Nepal", flag: "🇳🇵", minDigits: 10, maxDigits: 10 },
  { code: "+234", country: "Nigeria", flag: "🇳🇬", minDigits: 10, maxDigits: 10 },
  { code: "+968", country: "Oman", flag: "🇴🇲", minDigits: 8, maxDigits: 8 },
  { code: "+92", country: "Pakistan", flag: "🇵🇰", minDigits: 10, maxDigits: 10 },
  { code: "+970", country: "Palestine", flag: "🇵🇸", minDigits: 9, maxDigits: 9 },
  { code: "+63", country: "Philippines", flag: "🇵🇭", minDigits: 10, maxDigits: 10 },
  { code: "+974", country: "Qatar", flag: "🇶🇦", minDigits: 8, maxDigits: 8 },
  { code: "+7", country: "Russia", flag: "🇷🇺", minDigits: 10, maxDigits: 10 },
  { code: "+65", country: "Singapore", flag: "🇸🇬", minDigits: 8, maxDigits: 8 },
  { code: "+27", country: "South Africa", flag: "🇿🇦", minDigits: 9, maxDigits: 9 },
  { code: "+82", country: "South Korea", flag: "🇰🇷", minDigits: 9, maxDigits: 10 },
  { code: "+34", country: "Spain", flag: "🇪🇸", minDigits: 9, maxDigits: 9 },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰", minDigits: 9, maxDigits: 9 },
  { code: "+249", country: "Sudan", flag: "🇸🇩", minDigits: 9, maxDigits: 9 },
  { code: "+255", country: "Tanzania", flag: "🇹🇿", minDigits: 9, maxDigits: 9 },
  { code: "+66", country: "Thailand", flag: "🇹🇭", minDigits: 9, maxDigits: 9 },
  { code: "+216", country: "Tunisia", flag: "🇹🇳", minDigits: 8, maxDigits: 8 },
  { code: "+90", country: "Turkey", flag: "🇹🇷", minDigits: 10, maxDigits: 10 },
  { code: "+971", country: "UAE", flag: "🇦🇪", minDigits: 9, maxDigits: 9 },
  { code: "+256", country: "Uganda", flag: "🇺🇬", minDigits: 9, maxDigits: 9 },
  { code: "+44", country: "UK", flag: "🇬🇧", minDigits: 10, maxDigits: 10 },
  { code: "+1", country: "USA", flag: "🇺🇸", minDigits: 10, maxDigits: 10 },
  { code: "+84", country: "Vietnam", flag: "🇻🇳", minDigits: 9, maxDigits: 10 },
  { code: "+967", country: "Yemen", flag: "🇾🇪", minDigits: 9, maxDigits: 9 },
];
